import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'site.name': 'EL-YANIS Real Estate',
    'site.tagline': 'Your trusted partner in finding the perfect property across Algeria.',
    'nav.home': 'Home',
    'nav.listings': 'Listings',
    'nav.services': 'Services',
    'nav.agents': 'Agents',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'Find Your Dream Property in Algeria',
    'hero.subtitle': 'Discover the perfect home or investment opportunity with EL-YANIS Real Estate',
    'search.placeholder': 'Search by keyword or city...',
    'search.allTypes': 'All Types',
    'search.sale': 'For Sale',
    'search.rent': 'For Rent',
    'search.allCities': 'All Cities',
    'search.button': 'Search Properties',
    'features.premium.title': 'Premium Properties',
    'features.premium.desc': 'Curated selection of high-quality residential and commercial properties',
    'features.experts.title': 'Expert Agents',
    'features.experts.desc': 'Professional team with deep local market knowledge',
    'features.trusted.title': 'Trusted Service',
    'features.trusted.desc': 'Transparent process and dedicated support throughout your journey',
    'featured.title': 'Featured Properties',
    'featured.subtitle': 'Explore our latest and most popular listings',
    'featured.viewAll': 'View All Properties',
    'property.bedrooms': 'Bedrooms',
    'property.bathrooms': 'Bathrooms',
    'property.area': 'Area',
    'property.price': 'Price',
    'property.priceOnRequest': 'Price on request',
    'property.sale': 'For Sale',
    'property.rent': 'For Rent',
    'property.viewDetails': 'View Details',
    'property.description': 'Description',
    'property.amenities': 'Amenities',
    'property.contactAgent': 'Contact Agent',
    'contact.title': 'Get in Touch',
    'contact.subtitle': "Have questions? We're here to help you find your perfect property",
    'contact.info.title': 'Contact Information',
    'contact.info.desc': "Whether you're looking to buy, sell, or rent a property, our team is ready to assist you. Reach out to us through any of the following channels, and we'll get back to you as soon as possible.",
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.office': 'Office',
    'contact.whatsapp': 'WhatsApp',
    'contact.hours': 'Office Hours',
    'contact.hours.weekdays': 'Sunday - Thursday: 9:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Saturday: 9:00 AM - 6:00 PM',
    'contact.hours.friday': 'Friday: Closed',
    'contact.social.title': 'Connect With Us',
    'contact.social.desc': 'Follow us on social media for the latest property listings and updates',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Mohammed Beneddra',
    'contact.form.placeholder.email': 'beneddra.moha@gmail.com',
    'contact.form.placeholder.phone': '+213 555 123 456',
    'contact.form.placeholder.message': 'Tell us about your property needs...',
    'contact.form.sending': 'Sending...',
    'contact.form.sent': 'Message Sent',
    'contact.form.send': 'Send Message',
    'contact.form.success': "Thank you for your message! We'll get back to you soon.",
    'footer.quickLinks': 'Quick Links',
    'footer.propertiesSale': 'Properties for Sale',
    'footer.propertiesRent': 'Properties for Rent',
    'footer.ourAgents': 'Our Agents',
    'footer.aboutUs': 'About Us',
    'footer.followUs': 'Follow Us:',
    'footer.copyright': 'All rights reserved.',
    'services.title': 'Our Services',
    'services.subtitle': 'Professional real estate services tailored to your needs',
    'services.estimation.title': 'Property Estimation',
    'services.estimation.desc': 'Get an accurate and professional evaluation of your property with our expert estimation service.',
    'services.estimation.feature1': 'Detailed market analysis',
    'services.estimation.feature2': 'Comparative property assessment',
    'services.estimation.feature3': 'Professional evaluation report',
    'services.estimation.feature4': 'Free initial consultation',
    'services.accompagnement.title': 'Full Support',
    'services.accompagnement.desc': 'Complete assistance throughout your real estate journey, from search to final transaction.',
    'services.accompagnement.feature1': 'Personalized property search',
    'services.accompagnement.feature2': 'Property visit organization',
    'services.accompagnement.feature3': 'Negotiation assistance',
    'services.accompagnement.feature4': 'Administrative support',
    'services.conseil.title': 'Legal Advice',
    'services.conseil.desc': 'Expert legal guidance to ensure your real estate transactions are secure and compliant.',
    'services.conseil.feature1': 'Contract review and analysis',
    'services.conseil.feature2': 'Legal documentation assistance',
    'services.conseil.feature3': 'Property rights verification',
    'services.conseil.feature4': 'Transaction compliance',
    'services.contactUs': 'Contact Us',
    'services.cta.title': 'Ready to Get Started?',
    'services.cta.desc': 'Contact us today for a free consultation and let our experts guide you.',
    'services.cta.whatsapp': 'Chat on WhatsApp',
    'services.cta.call': 'Call Us Now',
    'services.why.title': 'Why Choose Our Services?',
    'services.why.desc': 'We combine expertise, speed, and quality to deliver exceptional results.',
    'services.why.expertise': 'Proven Expertise',
    'services.why.expertiseDesc': 'Years of experience in the Algerian real estate market',
    'services.why.fast': 'Fast Service',
    'services.why.fastDesc': 'Quick responses and efficient process management',
    'services.why.quality': 'Premium Quality',
    'services.why.qualityDesc': 'High standards of professionalism in every service',
    'about.title': 'About EL-YANIS Real Estate',
    'about.subtitle': 'Your trusted partner in Algerian real estate',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'At EL-YANIS Real Estate, we are committed to making property dreams come true. With years of experience in the Algerian market, we provide exceptional service and expert knowledge to help you find the perfect property.',
    'about.story.title': 'Our Story',
    'about.story.paragraph1': 'Founded with a vision to transform the real estate experience in Algeria, EL-YANIS Real Estate has become a trusted name in the industry. We specialize in connecting people with their dream properties, whether they\'re looking to buy, rent, or invest.',
    'about.story.paragraph2': 'Our team of experienced professionals brings deep market knowledge, unwavering dedication, and a customer-first approach to every transaction. We believe that finding the right property is about more than just square meters and prices—it\'s about finding a place to call home.',
    'about.values.transparency.title': 'Transparency',
    'about.values.transparency.desc': 'We believe in honest, clear communication at every step. No hidden fees, no surprises—just straightforward service.',
    'about.values.customerFirst.title': 'Customer First',
    'about.values.customerFirst.desc': 'Your satisfaction is our priority. We listen to your needs and work tirelessly to help you achieve your real estate goals.',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'We maintain the highest standards of professionalism and expertise in everything we do.',
    'about.why.title': 'Why Choose Us',
    'about.why.experience': 'Years of experience in the Algerian market',
    'about.why.listings': 'Diverse properties in prime locations',
    'about.why.team': 'Professional and dedicated team',
    'about.why.support': 'Comprehensive support from search to closing',
    'about.why.personalized': 'Personalized Service',
    'about.why.personalizedDesc': 'We take time to understand your unique needs and preferences to find the perfect match.',
    'about.why.endToEnd': 'End-to-End Support',
    'about.why.endToEndDesc': 'From property search to closing, we guide you through every step of your real estate journey.',
    'city.tlemcen': 'Tlemcen',
    'city.aintemouchent': 'Ain Temouchent',
    'city.sidibelabbes': 'Sidi Bel Abbès',
    'listings.title': 'Property Listings',
    'listings.subtitle': 'Discover your perfect property',
    'listings.noResults': 'No properties found matching your criteria',
    'listings.loading': 'Loading properties...',
    'agents.title': 'Our Real Estate Agents',
    'agents.subtitle': 'Meet our professional team',
    'agents.experience': 'Years Experience',
    'agents.properties': 'Properties Sold',
    'agents.contactAgent': 'Contact Agent',
  },
  ar: {
    'site.name': 'EL-YANIS للعقارات',
    'site.tagline': 'شريكك الموثوق في إيجاد العقار المثالي في الجزائر.',
    'nav.home': 'الرئيسية',
    'nav.listings': 'العقارات',
    'nav.services': 'الخدمات',
    'nav.agents': 'الوكلاء',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'اعثر على عقار أحلامك في الجزائر',
    'hero.subtitle': 'اكتشف المنزل المثالي أو فرصة الاستثمار مع EL-YANIS للعقارات',
    'search.placeholder': 'البحث بالكلمة أو المدينة...',
    'search.allTypes': 'كل الأنواع',
    'search.sale': 'للبيع',
    'search.rent': 'للإيجار',
    'search.allCities': 'كل المدن',
    'search.button': 'البحث عن العقارات',
    'features.premium.title': 'عقارات مميزة',
    'features.premium.desc': 'مجموعة مختارة من العقارات السكنية والتجارية عالية الجودة',
    'features.experts.title': 'وكلاء خبراء',
    'features.experts.desc': 'فريق محترف لديه معرفة عميقة بالسوق المحلي',
    'features.trusted.title': 'خدمة موثوقة',
    'features.trusted.desc': 'عملية شفافة ودعم مخصص طوال رحلتك',
    'featured.title': 'العقارات المميزة',
    'featured.subtitle': 'استكشف أحدث وأشهر قوائمنا',
    'featured.viewAll': 'عرض جميع العقارات',
    'property.bedrooms': 'غرف النوم',
    'property.bathrooms': 'الحمامات',
    'property.area': 'المساحة',
    'property.price': 'السعر',
    'property.priceOnRequest': 'السعر عند الطلب',
    'property.sale': 'للبيع',
    'property.viewDetails': 'عرض التفاصيل',
    'property.description': 'الوصف',
    'property.amenities': 'المرافق',
    'property.contactAgent': 'تواصل مع الوكيل',
    'property.rent': 'للإيجار',
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'هل لديك أسئلة؟ نحن هنا لمساعدتك في العثور على عقارك المثالي',
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.desc': 'سواء كنت تبحث عن شراء أو بيع أو استئجار عقار، فريقنا جاهز لمساعدتك. تواصل معنا من خلال أي من القنوات التالية، وسنعود إليك في أقرب وقت ممكن.',
    'contact.phone': 'الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.office': 'المكتب',
    'contact.whatsapp': 'واتساب',
    'contact.hours': 'ساعات العمل',
    'contact.hours.weekdays': 'الأحد - الخميس: 9:00 صباحًا - 6:00 مساءً',
    'contact.hours.saturday': 'السبت: 9:00 صباحًا - 6:00 مساءً',
    'contact.hours.friday': 'الجمعة: مغلق',
    'contact.social.title': 'تواصل معنا',
    'contact.social.desc': 'تابعنا على وسائل التواصل الاجتماعي لأحدث قوائم العقارات والتحديثات',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.name': 'اسمك',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.message': 'الرسالة',
    'contact.form.placeholder.name': 'محمد بن عدرة',
    'contact.form.placeholder.email': 'beneddra.moha@gmail.com',
    'contact.form.placeholder.phone': '0555 123 456 213+',
    'contact.form.placeholder.message': 'أخبرنا عن احتياجاتك العقارية...',
    'contact.form.sending': 'جاري الإرسال...',
    'contact.form.sent': 'تم إرسال الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.success': 'شكرًا على رسالتك! سنعود إليك قريبًا.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.propertiesSale': 'عقارات للبيع',
    'footer.propertiesRent': 'عقارات للإيجار',
    'footer.ourAgents': 'وكلاؤنا',
    'footer.aboutUs': 'من نحن',
    'footer.followUs': 'تابعنا:',
    'footer.copyright': 'جميع الحقوق محفوظة.',
    'services.title': 'خدماتنا',
    'services.subtitle': 'خدمات عقارية احترافية مصممة خصيصًا لاحتياجاتك',
    'services.estimation.title': 'تقييم العقارات',
    'services.estimation.desc': 'احصل على تقييم دقيق واحترافي لعقارك من خلال خدمة التقدير الخبيرة لدينا.',
    'services.estimation.feature1': 'تحليل مفصل للسوق',
    'services.estimation.feature2': 'تقييم مقارن للعقارات',
    'services.estimation.feature3': 'تقرير تقييم احترافي',
    'services.estimation.feature4': 'استشارة أولية مجانية',
    'services.accompagnement.title': 'المرافقة الكاملة',
    'services.accompagnement.desc': 'مساعدة كاملة طوال رحلتك العقارية، من البحث إلى المعاملة النهائية.',
    'services.accompagnement.feature1': 'بحث شخصي عن العقار',
    'services.accompagnement.feature2': 'تنظيم زيارات العقارات',
    'services.accompagnement.feature3': 'المساعدة في التفاوض',
    'services.accompagnement.feature4': 'الدعم الإداري',
    'services.conseil.title': 'الاستشارات القانونية',
    'services.conseil.desc': 'إرشادات قانونية خبيرة لضمان أن معاملاتك العقارية آمنة ومتوافقة.',
    'services.conseil.feature1': 'مراجعة وتحليل العقود',
    'services.conseil.feature2': 'المساعدة في التوثيق القانوني',
    'services.conseil.feature3': 'التحقق من حقوق الملكية',
    'services.conseil.feature4': 'امتثال المعاملات',
    'services.contactUs': 'اتصل بنا',
    'services.cta.title': 'هل أنت مستعد للبدء؟',
    'services.cta.desc': 'اتصل بنا اليوم للحصول على استشارة مجانية ودع خبرائنا يرشدونك.',
    'services.cta.whatsapp': 'تحدث على واتساب',
    'services.cta.call': 'اتصل بنا الآن',
    'services.why.title': 'لماذا تختار خدماتنا؟',
    'services.why.desc': 'نجمع بين الخبرة والسرعة والجودة لتقديم نتائج استثنائية.',
    'services.why.expertise': 'خبرة مثبتة',
    'services.why.expertiseDesc': 'سنوات من الخبرة في سوق العقارات الجزائري',
    'services.why.fast': 'خدمة سريعة',
    'services.why.fastDesc': 'استجابة سريعة وإدارة فعالة للعمليات',
    'services.why.quality': 'جودة ممتازة',
    'services.why.qualityDesc': 'معايير عالية من الاحترافية في كل خدمة',
    'about.title': 'عن EL-YANIS للعقارات',
    'about.subtitle': 'شريكك الموثوق في العقارات الجزائرية',
    'about.mission.title': 'مهمتنا',
    'about.mission.desc': 'في EL-YANIS للعقارات، نحن ملتزمون بجعل أحلام العقارات حقيقة. مع سنوات من الخبرة في السوق الجزائري، نقدم خدمة استثنائية ومعرفة خبيرة لمساعدتك في العثور على العقار المثالي.',
    'about.story.title': 'قصتنا',
    'about.story.paragraph1': 'تأسست EL-YANIS للعقارات برؤية لتحويل تجربة العقارات في الجزائر، وأصبحت اسمًا موثوقًا في الصناعة. نحن متخصصون في ربط الأشخاص بعقاراتهم المثالية، سواء كانوا يتطلعون للشراء أو الإيجار أو الاستثمار.',
    'about.story.paragraph2': 'يجلب فريقنا من المحترفين ذوي الخبرة معرفة عميقة بالسوق، وتفانيًا لا يتزعزع، ونهجًا يضع العميل أولاً في كل معاملة. نحن نؤمن أن العثور على العقار المناسب هو أكثر من مجرد أمتار مربعة وأسعار - إنه يتعلق بإيجاد مكان تسميه منزلك.',
    'about.values.transparency.title': 'الشفافية',
    'about.values.transparency.desc': 'نحن نؤمن بالتواصل الصادق والواضح في كل خطوة. لا توجد رسوم مخفية، ولا مفاجآت - فقط خدمة مباشرة.',
    'about.values.customerFirst.title': 'العميل أولاً',
    'about.values.customerFirst.desc': 'رضاك هو أولويتنا. نحن نستمع إلى احتياجاتك ونعمل بلا كلل لمساعدتك في تحقيق أهدافك العقارية.',
    'about.values.excellence.title': 'التميز',
    'about.values.excellence.desc': 'نحن نحافظ على أعلى معايير الاحترافية والخبرة في كل ما نقوم به.',
    'about.why.title': 'لماذا تختارنا',
    'about.why.experience': 'سنوات من الخبرة في السوق الجزائري',
    'about.why.listings': 'عقارات متنوعة في مواقع رئيسية',
    'about.why.team': 'فريق محترف ومخصص',
    'about.why.support': 'دعم شامل من البحث إلى الإغلاق',
    'about.why.personalized': 'خدمة شخصية',
    'about.why.personalizedDesc': 'نحن نأخذ الوقت الكافي لفهم احتياجاتك وتفضيلاتك الفريدة للعثور على التطابق المثالي.',
    'about.why.endToEnd': 'دعم شامل',
    'about.why.endToEndDesc': 'من البحث عن العقار إلى الإغلاق، نرشدك خلال كل خطوة من رحلتك العقارية.',
    'city.tlemcen': 'تلمسان',
    'city.aintemouchent': 'عين تموشنت',
    'city.sidibelabbes': 'سيدي بلعباس',
    'listings.title': 'قوائم العقارات',
    'listings.subtitle': 'اكتشف عقارك المثالي',
    'listings.noResults': 'لم يتم العثور على عقارات تطابق معاييرك',
    'listings.loading': 'جارٍ تحميل العقارات...',
    'agents.title': 'وكلاء العقارات لدينا',
    'agents.subtitle': 'تعرف على فريقنا المحترف',
    'agents.experience': 'سنوات من الخبرة',
    'agents.properties': 'عقارات مباعة',
    'agents.contactAgent': 'تواصل مع الوكيل',
  },
  fr: {
    'site.name': 'EL-YANIS Immobilier',
    'site.tagline': 'Votre partenaire de confiance pour trouver la propriété idéale en Algérie.',
    'nav.home': 'Accueil',
    'nav.listings': 'Annonces',
    'nav.services': 'Services',
    'nav.agents': 'Agents',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'hero.title': 'Trouvez la Propriété de Vos Rêves en Algérie',
    'hero.subtitle': "Découvrez la maison parfaite ou l'opportunité d'investissement avec EL-YANIS Immobilier",
    'search.placeholder': 'Rechercher par mot-clé ou ville...',
    'search.allTypes': 'Tous les types',
    'search.sale': 'À vendre',
    'search.rent': 'À louer',
    'search.allCities': 'Toutes les villes',
    'search.button': 'Rechercher des propriétés',
    'features.premium.title': 'Propriétés Premium',
    'features.premium.desc': 'Sélection soignée de propriétés résidentielles et commerciales de haute qualité',
    'features.experts.title': 'Agents Experts',
    'features.experts.desc': 'Équipe professionnelle avec une connaissance approfondie du marché local',
    'features.trusted.title': 'Service de Confiance',
    'features.trusted.desc': 'Processus transparent et soutien dédié tout au long de votre parcours',
    'featured.title': 'Propriétés en Vedette',
    'featured.subtitle': 'Explorez nos dernières annonces les plus populaires',
    'featured.viewAll': 'Voir toutes les propriétés',
    'property.bedrooms': 'Chambres',
    'property.bathrooms': 'Salles de bain',
    'property.area': 'Surface',
    'property.price': 'Prix',
    'property.priceOnRequest': 'Prix sur demande',
    'property.sale': 'À vendre',
    'property.viewDetails': 'Voir les détails',
    'property.description': 'Description',
    'property.amenities': 'Équipements',
    'property.contactAgent': 'Contacter l\'agent',
    'property.rent': 'À louer',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Des questions? Nous sommes là pour vous aider à trouver votre propriété idéale',
    'contact.info.title': 'Informations de Contact',
    'contact.info.desc': "Que vous cherchiez à acheter, vendre ou louer une propriété, notre équipe est prête à vous aider. Contactez-nous par l'un des canaux suivants, et nous vous répondrons dès que possible.",
    'contact.phone': 'Téléphone',
    'contact.email': 'Email',
    'contact.office': 'Bureau',
    'contact.whatsapp': 'WhatsApp',
    'contact.hours': "Heures d'ouverture",
    'contact.hours.weekdays': 'Dimanche - Jeudi: 9h00 - 18h00',
    'contact.hours.saturday': 'Samedi: 9h00 - 18h00',
    'contact.hours.friday': 'Vendredi: Fermé',
    'contact.social.title': 'Suivez-nous',
    'contact.social.desc': 'Suivez-nous sur les réseaux sociaux pour les dernières annonces et actualités',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.name': 'Votre nom',
    'contact.form.email': 'Adresse email',
    'contact.form.phone': 'Numéro de téléphone',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Mohammed Beneddra',
    'contact.form.placeholder.email': 'beneddra.moha@gmail.com',
    'contact.form.placeholder.phone': '+213 555 123 456',
    'contact.form.placeholder.message': 'Parlez-nous de vos besoins immobiliers...',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.sent': 'Message envoyé',
    'contact.form.send': 'Envoyer le message',
    'contact.form.success': 'Merci pour votre message! Nous vous répondrons bientôt.',
    'footer.quickLinks': 'Liens rapides',
    'footer.propertiesSale': 'Propriétés à vendre',
    'footer.propertiesRent': 'Propriétés à louer',
    'footer.ourAgents': 'Nos agents',
    'footer.aboutUs': 'À propos de nous',
    'footer.followUs': 'Suivez-nous:',
    'footer.copyright': 'Tous droits réservés.',
    'services.title': 'Nos Services',
    'services.subtitle': 'Services immobiliers professionnels adaptés à vos besoins',
    'services.estimation.title': 'Estimation Immobilière',
    'services.estimation.desc': 'Obtenez une évaluation précise et professionnelle de votre propriété avec notre service d\'estimation expert.',
    'services.estimation.feature1': 'Analyse détaillée du marché',
    'services.estimation.feature2': 'Évaluation comparative des propriétés',
    'services.estimation.feature3': 'Rapport d\'évaluation professionnel',
    'services.estimation.feature4': 'Consultation initiale gratuite',
    'services.accompagnement.title': 'Accompagnement Complet',
    'services.accompagnement.desc': 'Assistance complète tout au long de votre parcours immobilier, de la recherche à la transaction finale.',
    'services.accompagnement.feature1': 'Recherche personnalisée de propriété',
    'services.accompagnement.feature2': 'Organisation de visites',
    'services.accompagnement.feature3': 'Assistance à la négociation',
    'services.accompagnement.feature4': 'Support administratif',
    'services.conseil.title': 'Conseil Juridique',
    'services.conseil.desc': 'Conseils juridiques experts pour garantir que vos transactions immobilières sont sécurisées et conformes.',
    'services.conseil.feature1': 'Examen et analyse des contrats',
    'services.conseil.feature2': 'Assistance à la documentation légale',
    'services.conseil.feature3': 'Vérification des droits de propriété',
    'services.conseil.feature4': 'Conformité des transactions',
    'services.contactUs': 'Contactez-nous',
    'services.cta.title': 'Prêt à Commencer?',
    'services.cta.desc': 'Contactez-nous dès aujourd\'hui pour une consultation gratuite et laissez nos experts vous guider.',
    'services.cta.whatsapp': 'Discuter sur WhatsApp',
    'services.cta.call': 'Appelez-nous',
    'services.why.title': 'Pourquoi Choisir Nos Services?',
    'services.why.desc': 'Nous combinons expertise, rapidité et qualité pour offrir des résultats exceptionnels.',
    'services.why.expertise': 'Expertise Prouvée',
    'services.why.expertiseDesc': 'Des années d\'expérience sur le marché immobilier algérien',
    'services.why.fast': 'Service Rapide',
    'services.why.fastDesc': 'Réponses rapides et gestion efficace des processus',
    'services.why.quality': 'Qualité Premium',
    'services.why.qualityDesc': 'Normes élevées de professionnalisme dans chaque service',
    'about.title': 'À propos de EL-YANIS Immobilier',
    'about.subtitle': 'Votre partenaire de confiance en immobilier algérien',
    'about.mission.title': 'Notre Mission',
    'about.mission.desc': "Chez EL-YANIS Immobilier, nous nous engageons à réaliser les rêves immobiliers. Avec des années d'expérience sur le marché algérien, nous offrons un service exceptionnel et une expertise pour vous aider à trouver la propriété idéale.",
    'about.story.title': 'Notre histoire',
    'about.story.paragraph1': "Fondée avec la vision de transformer l'expérience immobilière en Algérie, EL-YANIS Immobilier est devenue un nom de confiance dans l'industrie. Nous sommes spécialisés dans la mise en relation des personnes avec leurs propriétés de rêve, qu'ils cherchent à acheter, louer ou investir.",
    'about.story.paragraph2': "Notre équipe de professionnels expérimentés apporte une connaissance approfondie du marché, un dévouement inébranlable et une approche axée sur le client à chaque transaction. Nous croyons que trouver la bonne propriété, c'est plus que des mètres carrés et des prix - c'est trouver un endroit qu'on appelle maison.",
    'about.values.transparency.title': 'Transparence',
    'about.values.transparency.desc': 'Nous croyons en une communication honnête et claire à chaque étape. Pas de frais cachés, pas de surprises - juste un service direct.',
    'about.values.customerFirst.title': 'Le client d\'abord',
    'about.values.customerFirst.desc': 'Votre satisfaction est notre priorité. Nous écoutons vos besoins et travaillons sans relâche pour vous aider à atteindre vos objectifs immobiliers.',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Nous maintenons les plus hauts standards de professionnalisme et d\'expertise dans tout ce que nous faisons.',
    'about.why.title': 'Pourquoi nous choisir',
    'about.why.experience': "Années d'expérience sur le marché algérien",
    'about.why.listings': 'Propriétés diversifiées dans des emplacements de choix',
    'about.why.team': 'Équipe professionnelle et dévouée',
    'about.why.support': 'Support complet de la recherche à la conclusion',
    'about.why.personalized': 'Service personnalisé',
    'about.why.personalizedDesc': 'Nous prenons le temps de comprendre vos besoins et préférences uniques pour trouver la correspondance parfaite.',
    'about.why.endToEnd': 'Support de bout en bout',
    'about.why.endToEndDesc': 'De la recherche de propriété à la conclusion, nous vous guidons à travers chaque étape de votre parcours immobilier.',
    'city.tlemcen': 'Tlemcen',
    'city.aintemouchent': 'Ain Temouchent',
    'city.sidibelabbes': 'Sidi Bel Abbès',
    'listings.title': 'Annonces Immobilières',
    'listings.subtitle': 'Découvrez votre propriété idéale',
    'listings.noResults': 'Aucune propriété trouvée correspondant à vos critères',
    'listings.loading': 'Chargement des propriétés...',
    'agents.title': 'Nos Agents Immobiliers',
    'agents.subtitle': 'Rencontrez notre équipe professionnelle',
    'agents.experience': "Années d'expérience",
    'agents.properties': 'Propriétés vendues',
    'agents.contactAgent': "Contacter l'agent",
  },
};
